pharma_analytics:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('AZURE_SQL_SERVER') }}"
      database: "{{ env_var('AZURE_SQL_DB') }}"
      schema: staging
      username: "{{ env_var('AZURE_SQL_USER') }}"
      password: "{{ env_var('AZURE_SQL_PASSWORD') }}"
      port: 1433
      threads: 4
      encrypt: true
      trust_cert: false
